env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  o-console: 0
  import/extensions: 0
  "no-param-reassign": 0